name: pifand # you probably want to 'snapcraft register <name>'
title: PiFan Daemon
base: core18 # the base snap is the execution environment for this snap
version: '0.2+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Manages 3 and 4-pin fans connected to the Raspberry Pi's GPIO pins.
description: |
  PiFan is a background service used for running and managing cooling fans connected to the Raspberry Pi's
  GPIO pins. 
license: GPL-3.0

architectures:
  - build-on: amd64
    run-on: amd64
  
  - build-on: armhf
    run-on: armhf

  - build-on: arm64
    run-on: arm64

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  pifand:
    command: bin/pifand
    daemon: simple
    stop-timeout: 10s

parts:
  link-jsoncpp:
    plugin: nil

    override-build: |
      ln -s /usr/include/jsoncpp/json/ /usr/include/json

  pigpio:
    plugin: make
    source: https://github.com/joan2937/pigpio/archive/master.zip
    source-type: zip

    build-packages:
      - gcc
      - python-setuptools
      - python3-setuptools

    override-build: |
      cd pigpio-master
      make
      make install
      #mkdir -p $SNAPCRAFT_STAGE/usr/local/lib/
      cp /usr/local/lib/libpigpiod_if2.so.1 ./libpigpiod_if2.so.1
      install -d $SNAPCRAFT_STAGE/usr/local/lib/
      install -D libpigpiod_if2.so.1 $SNAPCRAFT_STAGE/usr/local/lib/
    
    
  # pigpio-libs:
  #   plugin: nil
  #   after:
  #     - pigpio

  #   override-build: |
  #       cp /usr/local/lib/libpigpiod_if2.so.1 ./libpigpiod_if2.so.1
  #       install -D libpigpiod_if2.so.1 ../install/usr/local/lib/

  pifand:
    after:
      - pigpio
      - link-jsoncpp
    # See 'snapcraft plugins'
    plugin: cmake
    #source: https://github.com/iAmSomeone2/pifan.git
    source: .
    #source-type: git
    source-type: local
    #source-depth: 1
    #source-branch: master
    
    build-environment:
      - CC: /usr/bin/clang
      - CXX: /usr/bin/clang++

    build-packages: 
      - pkg-config
      - clang
      - libjsoncpp-dev

    stage-packages:
      - libjsoncpp1

    # filesets:
    #   pigpio-libs:
    #     - $SNAPCRAFT_STAGE/usr/local/lib/libpigpiod_if2.so.1
        
    # prime:
    #   - $pigpio-libs

    configflags:
      - -DCMAKE_BUILD_TYPE=Release