name: pifand # you probably want to 'snapcraft register <name>'
title: PiFan Daemon
base: core18 # the base snap is the execution environment for this snap
version: '0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Manages 3 and 4-pin fans connected to the Raspberry Pi's GPIO pins.
description: |
  PiFan is a background service used for running and managing cooling fans connected to the Raspberry Pi's
  GPIO pins. 
license: GPL-3.0

architectures:
  - build-on: amd64
    run-on: amd64
  
  - build-on: armhf
    run-on: armhf

  - build-on: arm64
    run-on: arm64

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  pifand:
    command: bin/pifand
    daemon: simple
    stop-timeout: 10s
    #socket: 
    #  - /run/user/1000/pifand/pifand-socket
    #plugs:
    #  - network-bind

parts:
  link-jsoncpp:
    plugin: nil

    override-build: |
      ln -s /usr/include/jsoncpp/json/ /usr/include/json

  pigpio:
    plugin: make
    source: https://github.com/joan2937/pigpio/archive/master.zip
    source-type: zip

    build-packages:
      - gcc
      - python-setuptools
      - python3-setuptools

    override-build: |
      cd pigpio-master
      make
      make install
      #mkdir -p $SNAPCRAFT_STAGE/usr/local/lib/
      cp /usr/local/lib/libpigpiod_if2.so.1 ../libpigpiod_if2.so.1
      cp /usr/local/lib/libpigpiod_if.so.1 ../libpigpiod_if.so.1
      cp /usr/local/lib/libpigpio.so.1 ../libpigpio.so.1
      install -d ../../install/
      install -D ../libpigpiod_if2.so.1 ../../install/
      install -D ../libpigpiod_if.so.1 ../../install/
      install -D ../libpigpio.so.1 ../../install/

    organize:
      libpigpiod_if2.so.1: usr/local/lib/libpigpiod_if2.so.1
      libpigpiod_if.so.1: usr/local/lib/libpigpiod_if.so.1
      libpigpio.so.1: usr/local/lib/libpigpio.so.1

    stage:
      - usr/local/lib/libpigpiod_if2.so.1
      - usr/local/lib/libpigpiod_if.so.1
      - usr/local/lib/libpigpio.so.1

    prime:
      - usr/local/lib/libpigpiod_if2.so.1
      - usr/local/lib/libpigpiod_if.so.1
      - usr/local/lib/libpigpio.so.1
    

  pifand:
    after:
      - pigpio
      - link-jsoncpp
    # See 'snapcraft plugins'
    plugin: cmake
    source: .
    source-type: local
    
    build-environment:
      - CC: /usr/bin/clang
      - CXX: /usr/bin/clang++

    build-packages: 
      - pkg-config
      - clang
      - libjsoncpp-dev
      - libboost-dev
      - libboost-filesystem-dev

    stage-packages:
      - libjsoncpp1
      - libboost-filesystem1.65.1

    configflags:
      - -DCMAKE_BUILD_TYPE=Release